import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "./providers";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ConvexClientProvider>
      <html lang="en">
        <body className={cn("min-h-screen font-sans dark")}>{children}</body>
      </html>
    </ConvexClientProvider>
  );
}
